### ISSUE TITLE
Protección de Shells

### ISSUE THREAD

**Issue by agucova** [icodeart/upload-php#1]
Este upload tiene verificación de extensión? Se puede subir un shell?

**Comment by icodeart** [comment]
Si estimado, el upload verifica el tipo de archivo que se esta subiendo, con un whitelist que tu defines, revisa la actualización que se hizo hoy, donde ademas verifica el mimetype del archivo, para definir un tipo de archivo permitido, debes agregar su extensión en la linea 28, ejemplo: .pdf y también agregar su mimetype en la linea 30, en este caso seria application/pdf.
